apiVersion: v1
kind: Service
metadata:
  name: supply-chain-example-client-slim
spec:
  selector:
    app: supply-chain-example-client-slim
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supply-chain-example-client-slim
  namespace: supply-chain-demo-slim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supply-chain-example-client-slim
  template:
    metadata:
      labels:
        app: supply-chain-example-client-slim
    spec:
      containers:
        - name: app
          image: joshbressers/supply-chain-example-client:slim
          ports:
            - containerPort: 3000
          env:
            - name: SERVERURL
              value: http://supply-chain-example-server-slim:8888
          imagePullPolicy: Always
